services:
  mysql:
    image: mysql
    container_name: mysql-production-container
    ports:
      - "${MYSQL_TCP_PORT}:${MYSQL_TCP_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_TCP_PORT=${MYSQL_TCP_PORT}
  server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "${PORT}:${PORT}"
    container_name: server-production-container
    depends_on:
      - mysql
    volumes:
      - ./src:/server/src
      - /var/run/docker.sock:/var/run/docker.sock
      - ./files:/server/files  
  