FROM node:20

WORKDIR /server-prod

COPY package.json package-lock.json ./

RUN npm install
RUN npm rebuild bcrypt --build-from-soruce

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run" ,"start:prod"]